sudo: required

os:
  - linux
  - osx

addons:
  homebrew:
    update: false

install: true

before_install:
  - curl https://raw.githubusercontent.com/mattpaletta/scripts/master/build.sh | sh

script:
  - sh install.sh -a

notifications:
  email:
    on_failure: change
    on_success: never
