sudo: required

os:
  - linux
  - osx

addons:
  homebrew:
    update: false

install: true

before_install:
  - bash build.sh

script:
  - bash install.sh -a

notifications:
  email:
    on_failure: change
    on_success: never
