sudo: required

os:
  - linux
  - osx

addons:
  homebrew:
    update: false

install: true

script:
  - curl https://raw.githubusercontent.com/mattpaletta/scripts/master/install.sh | sudo sh

notifications:
  email:
    on_failure: change
    on_success: never
